INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),25,'Cingulo dorado','Cingulo para salida procesional','https://i.pinimg.com/originals/8a/d8/8f/8ad88f5284b36bda1ccd83723f451030.jpg','2022-05-19',4);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),10,'Llamador en miniatura de Nuestro Padre Jesús de las penas','Llamador de nuestro padre Jesus de las penas en miniatura perfecto para que tu hijo empiece a sentir el veneno por dentro','https://i.pinimg.com/originals/02/d7/00/02d7008fe10c73af21ad32cfeab628c3.jpg','2022-05-19',5);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),18.20,'Tulipas misterio ','Tulipas réplicas de las que usa Nuestro Padre Jesus de las Penas en su salida procesional','https://i.pinimg.com/originals/e5/ee/51/e5ee518129436a09eea9ea1856d70176.jpg','2022-05-19',4);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),30,'Jarras misterio','Replica de una jarra del misterio, ideal para decorar en casa','https://i.pinimg.com/originals/a5/50/1e/a5501e5f203c4abdfb1b613232a36543.jpg','2022-06-05',8);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),5.95,'Incienso procesional cristo','Paquetito de 100 g que contiene el incienso que se usa el Domingo de Ramos en el misterio durante la salida procesional','https://inciensosdesevilla.es/330-home_default/coronacion.jpg','2022-05-25',50);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),10,'Incienso procesional virgen','Paquetito de 100 g que contiene el incienso que se usa el Domingo de Ramos en el palio durante la salida procesional','https://inciensosdesevilla.es/1234-home_default/mi-madruga.jpg','2022-05-08',100);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),25,'Medalla Hermandad','Medalla oficial de la hermandad para los actos.','https://i.pinimg.com/originals/96/1d/8d/961d8db8968f3733f83819c80ea00381.jpg','2022-03-19',200);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),10,'Sudadera costalero ','Sudadera con cremallera ideal para el costalero el día de la salida','https://i.pinimg.com/originals/07/c6/98/07c698e8c63c3b939ca6c5892c5a90ad.jpg','2022-04-26',60);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),90,'Niño montañes con tunica procesional','Niño montañes ataviado con tunica procesional, ideal para decorar el salon de tu abuela','https://i.pinimg.com/originals/31/28/fe/3128fea028e2fb14e0b69aef379d1196.jpg','2022-05-19',4);
INSERT INTO PRODUCTO (ID, PVP, NOMBRE,DESCRIPCION,IMAGEN,FECHA_DE_ENTRADA,UNIDADES_STOCK) VALUES (NEXTVAL('hibernate_sequence'),10,'Nazareno inciensario ','Inciensario perfecto para aromar tu casa con los mejores olores cofrades.','https://i.pinimg.com/originals/96/93/92/969392ccdd08129dd1ca1cb4aab4d67b.jpg','2022-04-19',5);

